#!/usr/bin/env python3
"""Deterministic seed-event generator for the nightly usage-rollup batch job.

Produces a newline-delimited JSON (NDJSON) file of AnalyticsEvent records spread
across a fixed set of UTC days. Fully deterministic: the same invocation always
produces byte-identical output, so the batch job's aggregated rollups are
verifiable in tests and demos.

Usage:
    python3 generate_seed_events.py [output_path]

Default output: ../src/main/resources/seed/usage-events.ndjson
"""
from __future__ import annotations

import json
import os
import sys
import uuid

# Fixed UTC days the seed spans. Keeping this explicit (rather than "today - N")
# guarantees the rollup output is stable regardless of when the generator runs.
DAYS = ["2024-03-01", "2024-03-02", "2024-03-03"]

USERS = [f"user-{i:02d}" for i in range(1, 9)]

# (event_type, resource_type, per-day count). Ordering is fixed for determinism.
EVENT_PLAN = [
    ("document.created", "document", 4),
    ("document.viewed", "document", 9),
    ("document.edited", "document", 5),
    ("document.shared", "document", 2),
    ("file.uploaded", "file", 6),
    ("file.downloaded", "file", 7),
    ("collab.session_started", "document", 3),
    ("collab.session_ended", "document", 3),
    ("user.logged_in", "session", 8),
    ("storage.allocated", "file", 6),
    ("storage.released", "file", 2),
]

# Deterministic UUID namespace so event IDs are stable across runs.
NS = uuid.UUID("11111111-2222-3333-4444-555555555555")


def deterministic_uuid(*parts: object) -> str:
    return str(uuid.uuid5(NS, "|".join(str(p) for p in parts)))


def build_events() -> list[dict]:
    events: list[dict] = []
    for day in DAYS:
        # Seconds counter keeps timestamps ordered and unique within a day.
        second = 0
        for event_type, resource_type, count in EVENT_PLAN:
            for i in range(count):
                user = USERS[i % len(USERS)]
                resource_id = f"{resource_type}-{(i % 5) + 1:03d}"
                hh = (second // 3600) % 24
                mm = (second // 60) % 60
                ss = second % 60
                timestamp = f"{day}T{hh:02d}:{mm:02d}:{ss:02d}Z"
                metadata: dict[str, str] = {"source": "seed"}
                if event_type in ("storage.allocated", "storage.released"):
                    # 1 MiB per storage event -> deterministic byte totals.
                    metadata["bytes"] = str(1024 * 1024)
                if resource_type == "document":
                    metadata["title"] = f"Document {resource_id}"
                events.append(
                    {
                        "eventId": deterministic_uuid(day, event_type, i),
                        "eventType": event_type,
                        "userId": user,
                        "resourceId": resource_id,
                        "resourceType": resource_type,
                        "metadata": metadata,
                        "timestamp": timestamp,
                    }
                )
                second += 37  # fixed stride
    return events


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    default_out = os.path.join(
        here, "..", "src", "main", "resources", "seed", "usage-events.ndjson"
    )
    out_path = sys.argv[1] if len(sys.argv) > 1 else default_out
    out_path = os.path.abspath(out_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    events = build_events()
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("# Deterministic seed events for the nightly usage-rollup batch job.\n")
        fh.write("# Generated by scripts/generate_seed_events.py -- do not edit by hand.\n")
        for event in events:
            fh.write(json.dumps(event, separators=(",", ":"), sort_keys=True))
            fh.write("\n")

    print(f"Wrote {len(events)} events across {len(DAYS)} days to {out_path}")


if __name__ == "__main__":
    main()
