require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/ParameterLists:
  Max: 8

Metrics/AbcSize:
  Max: 35
