source 'https://rubygems.org'
ruby '~> 3.3.0'

gem 'active_model_serializers', '~> 0.10'
gem 'bootsnap', require: false
gem 'jbuilder', '~> 2.11'
gem 'jwt', '~> 2.8'
gem 'kaminari', '~> 1.2'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'rack-attack', '~> 6.7'
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.1.3'
gem 'redis', '~> 5.1'
gem 'sidekiq', '~> 7.2'

# Observability
gem 'lograge', '~> 0.14'
gem 'opentelemetry-instrumentation-rails', '~> 0.30'
gem 'opentelemetry-sdk', '~> 1.4'
gem 'prometheus_exporter', '~> 2.1'

group :development, :test do
  gem 'debug', platforms: %i[mri]
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.3'
  gem 'rspec-rails', '~> 6.1'
  gem 'rubocop', '~> 1.62', require: false
  gem 'rubocop-rails', '~> 2.24', require: false
  gem 'rubocop-rspec', '~> 2.27', require: false
end

group :test do
  gem 'database_cleaner-active_record', '~> 2.1'
  gem 'shoulda-matchers', '~> 6.1'
  gem 'simplecov', require: false
end
