-- Creates the OLTP owner (COMMISSION_PAY) and the OLAP owner (COMMISSION_DW)
-- inside the FREEPDB1 pluggable database. Run as SYSTEM against FREEPDB1.
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER commission_pay IDENTIFIED BY commission_pay
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE VIEW, CREATE TYPE TO commission_pay;

CREATE USER commission_dw IDENTIFIED BY commission_dw
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE,
      CREATE VIEW, CREATE MATERIALIZED VIEW TO commission_dw;

-- The warehouse reads from the OLTP schema during ETL.
GRANT SELECT ANY TABLE ON SCHEMA commission_pay TO commission_dw;

EXIT;
