import { Incident } from '../../models/incident.model';

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'inc-001',
    title: 'Search service returning 500 errors on autocomplete',
    description: 'Users are reporting that the autocomplete/suggest endpoint in the search service is returning HTTP 500 errors intermittently. The full-text search endpoint appears to work fine. MeiliSearch health check passes but the Flask application may have a bug in the suggest route handler.',
    severity: 'high',
    status: 'open',
    affectedService: 'search-service',
    devinSessionId: null,
    devinSessionUrl: null,
    devinSessionStatus: null,
    reporterId: 'usr-admin-01',
    resolvedAt: null,
    closedAt: null,
    active: true,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-002',
    title: 'File upload fails for files larger than 50MB',
    description: 'The file service is rejecting multipart uploads exceeding 50MB with a 413 Payload Too Large error. The Actix-Web configuration may have a body size limit that needs to be increased. S3 presigned uploads are not affected.',
    severity: 'medium',
    status: 'open',
    affectedService: 'file-service',
    devinSessionId: null,
    devinSessionUrl: null,
    devinSessionStatus: null,
    reporterId: 'usr-admin-01',
    resolvedAt: null,
    closedAt: null,
    active: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-003',
    title: 'Notification service SQS consumer backlog growing',
    description: 'The SQS queue otterworks-notifications has over 5000 messages in backlog. The Kotlin notification service consumer appears to be processing messages slowly. Possible memory pressure or SES rate limiting causing delays in email delivery.',
    severity: 'critical',
    status: 'open',
    affectedService: 'notification-service',
    devinSessionId: null,
    devinSessionUrl: null,
    devinSessionStatus: null,
    reporterId: 'usr-admin-02',
    resolvedAt: null,
    closedAt: null,
    active: true,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];
