apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.platformNamespace }}
  labels:
    {{- include "demo-platform.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ .Values.platformNamespace }}
