-- Commission Pay OLTP schema (owner: COMMISSION_PAY).
-- Agents, products, policies, commission rates, split allocations, and the
-- commission ledger the calculation procedures write into.
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE agents (
    agent_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    agent_code    VARCHAR2(16)  NOT NULL UNIQUE,
    full_name     VARCHAR2(120) NOT NULL,
    license_no    VARCHAR2(32)  NOT NULL UNIQUE,
    status        VARCHAR2(12)  DEFAULT 'ACTIVE' NOT NULL
                  CONSTRAINT ck_agents_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'TERMINATED')),
    hired_date    DATE          DEFAULT SYSDATE NOT NULL
);

CREATE TABLE products (
    product_code  VARCHAR2(16)  PRIMARY KEY,
    product_name  VARCHAR2(120) NOT NULL,
    line_of_business VARCHAR2(24) NOT NULL
                  CONSTRAINT ck_products_lob CHECK (line_of_business IN ('AUTO', 'HOME', 'LIFE', 'COMMERCIAL'))
);

-- Commission rates: agent_id NULL means the product default rate. Rates are
-- effective-dated; an open rate has effective_to = NULL. The management
-- procedures enforce non-overlap by closing the prior open rate.
CREATE TABLE commission_rates (
    rate_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_code  VARCHAR2(16)  NOT NULL REFERENCES products (product_code),
    agent_id      NUMBER        REFERENCES agents (agent_id),
    rate_pct      NUMBER(5, 2)  NOT NULL
                  CONSTRAINT ck_rates_range CHECK (rate_pct > 0 AND rate_pct <= 50),
    effective_from DATE         NOT NULL,
    effective_to   DATE,
    created_by    VARCHAR2(64)  NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_rates_dates CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE UNIQUE INDEX ux_rates_open ON commission_rates (
    product_code,
    NVL(agent_id, -1),
    CASE WHEN effective_to IS NULL THEN 0 END
);

CREATE TABLE policies (
    policy_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_no     VARCHAR2(24)  NOT NULL UNIQUE,
    product_code  VARCHAR2(16)  NOT NULL REFERENCES products (product_code),
    holder_name   VARCHAR2(120) NOT NULL,
    annual_premium NUMBER(12, 2) NOT NULL CHECK (annual_premium > 0),
    issued_date   DATE          NOT NULL,
    status        VARCHAR2(12)  DEFAULT 'IN_FORCE' NOT NULL
                  CONSTRAINT ck_policies_status CHECK (status IN ('IN_FORCE', 'LAPSED', 'CANCELLED'))
);

-- Split-commission allocation: which agents share a policy's commission and
-- in what proportion. Percentages for a policy must total exactly 100
-- (enforced by commission_pkg.set_commission_splits).
CREATE TABLE commission_splits (
    split_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_id     NUMBER        NOT NULL REFERENCES policies (policy_id),
    agent_id      NUMBER        NOT NULL REFERENCES agents (agent_id),
    split_pct     NUMBER(5, 2)  NOT NULL
                  CONSTRAINT ck_splits_range CHECK (split_pct > 0 AND split_pct <= 100),
    CONSTRAINT ux_splits_policy_agent UNIQUE (policy_id, agent_id)
);

-- Ledger the calculation procedure writes. One row per agent per policy per
-- period; re-running a period for a policy replaces its rows.
CREATE TABLE commission_ledger (
    ledger_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    policy_id     NUMBER        NOT NULL REFERENCES policies (policy_id),
    agent_id      NUMBER        NOT NULL REFERENCES agents (agent_id),
    period_month  VARCHAR2(7)   NOT NULL,  -- YYYY-MM
    rate_id       NUMBER        NOT NULL REFERENCES commission_rates (rate_id),
    split_pct     NUMBER(5, 2)  NOT NULL,
    base_premium  NUMBER(12, 2) NOT NULL,
    commission_amt NUMBER(12, 2) NOT NULL,
    calculated_at TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ux_ledger_row UNIQUE (policy_id, agent_id, period_month)
);

-- Audit trail every management procedure writes to.
CREATE TABLE rate_audit_log (
    audit_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    action        VARCHAR2(32)  NOT NULL,
    product_code  VARCHAR2(16),
    agent_id      NUMBER,
    policy_id     NUMBER,
    detail        VARCHAR2(400),
    actor         VARCHAR2(64)  NOT NULL,
    logged_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

EXIT;
