-- Deterministic test data for the Commission Pay OLTP schema.
WHENEVER SQLERROR EXIT SQL.SQLCODE

INSERT INTO agents (agent_id, agent_code, full_name, license_no, status, hired_date) VALUES
    (1, 'AG-100', 'Maria Alvarez',  'LIC-TX-55001', 'ACTIVE',     DATE '2018-03-12');
INSERT INTO agents (agent_id, agent_code, full_name, license_no, status, hired_date) VALUES
    (2, 'AG-101', 'James Okafor',   'LIC-TX-55002', 'ACTIVE',     DATE '2019-07-01');
INSERT INTO agents (agent_id, agent_code, full_name, license_no, status, hired_date) VALUES
    (3, 'AG-102', 'Priya Natarajan','LIC-TX-55003', 'ACTIVE',     DATE '2020-01-15');
INSERT INTO agents (agent_id, agent_code, full_name, license_no, status, hired_date) VALUES
    (4, 'AG-103', 'Dale Whitfield', 'LIC-TX-55004', 'SUSPENDED',  DATE '2017-11-30');

INSERT INTO products (product_code, product_name, line_of_business) VALUES
    ('AUTO-STD',  'Standard Auto',        'AUTO');
INSERT INTO products (product_code, product_name, line_of_business) VALUES
    ('HOME-PLUS', 'HomeOwners Plus',      'HOME');
INSERT INTO products (product_code, product_name, line_of_business) VALUES
    ('TERM-20',   '20-Year Term Life',    'LIFE');

-- Product default rates (agent_id NULL) plus one agent-specific override.
INSERT INTO commission_rates (rate_id, product_code, agent_id, rate_pct, effective_from, effective_to, created_by) VALUES
    (1, 'AUTO-STD',  NULL, 8.00,  DATE '2024-01-01', NULL, 'seed');
INSERT INTO commission_rates (rate_id, product_code, agent_id, rate_pct, effective_from, effective_to, created_by) VALUES
    (2, 'HOME-PLUS', NULL, 10.00, DATE '2024-01-01', NULL, 'seed');
INSERT INTO commission_rates (rate_id, product_code, agent_id, rate_pct, effective_from, effective_to, created_by) VALUES
    (3, 'TERM-20',   NULL, 15.00, DATE '2024-01-01', NULL, 'seed');
INSERT INTO commission_rates (rate_id, product_code, agent_id, rate_pct, effective_from, effective_to, created_by) VALUES
    (4, 'AUTO-STD',  1,    9.50,  DATE '2024-06-01', NULL, 'seed');

INSERT INTO policies (policy_id, policy_no, product_code, holder_name, annual_premium, issued_date, status) VALUES
    (1, 'POL-2025-0001', 'AUTO-STD',  'Chen Household',    1800.00, DATE '2025-02-10', 'IN_FORCE');
INSERT INTO policies (policy_id, policy_no, product_code, holder_name, annual_premium, issued_date, status) VALUES
    (2, 'POL-2025-0002', 'HOME-PLUS', 'Robinson Family',   2400.00, DATE '2025-03-05', 'IN_FORCE');
INSERT INTO policies (policy_id, policy_no, product_code, holder_name, annual_premium, issued_date, status) VALUES
    (3, 'POL-2025-0003', 'TERM-20',   'S. Gutierrez',      1200.00, DATE '2025-04-20', 'IN_FORCE');
INSERT INTO policies (policy_id, policy_no, product_code, holder_name, annual_premium, issued_date, status) VALUES
    (4, 'POL-2025-0004', 'AUTO-STD',  'Kowalski LLC Fleet',9600.00, DATE '2025-05-01', 'IN_FORCE');
INSERT INTO policies (policy_id, policy_no, product_code, holder_name, annual_premium, issued_date, status) VALUES
    (5, 'POL-2025-0005', 'HOME-PLUS', 'Ncube Residence',   2000.00, DATE '2025-05-15', 'LAPSED');

-- Policy 1: sole agent. Policy 2: two-way split. Policy 4: three-way split.
INSERT INTO commission_splits (policy_id, agent_id, split_pct) VALUES (1, 1, 100.00);
INSERT INTO commission_splits (policy_id, agent_id, split_pct) VALUES (2, 1, 60.00);
INSERT INTO commission_splits (policy_id, agent_id, split_pct) VALUES (2, 2, 40.00);
INSERT INTO commission_splits (policy_id, agent_id, split_pct) VALUES (4, 1, 50.00);
INSERT INTO commission_splits (policy_id, agent_id, split_pct) VALUES (4, 2, 30.00);
INSERT INTO commission_splits (policy_id, agent_id, split_pct) VALUES (4, 3, 20.00);

-- The seed inserts explicit IDs, which BY DEFAULT identity columns do not
-- consume; realign each identity sequence past the seeded values.
ALTER TABLE agents MODIFY agent_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE commission_rates MODIFY rate_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE policies MODIFY policy_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

COMMIT;
EXIT;
