-- Commission analytics star schema (owner: COMMISSION_DW).
-- Fed from the COMMISSION_PAY OLTP schema by dw_etl_pkg.load_commission_facts.
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE dim_agent (
    agent_key    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    agent_id     NUMBER        NOT NULL UNIQUE,
    agent_code   VARCHAR2(16)  NOT NULL,
    full_name    VARCHAR2(120) NOT NULL,
    status       VARCHAR2(12)  NOT NULL
);

CREATE TABLE dim_product (
    product_key      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product_code     VARCHAR2(16) NOT NULL UNIQUE,
    product_name     VARCHAR2(120) NOT NULL,
    line_of_business VARCHAR2(24) NOT NULL
);

CREATE TABLE dim_period (
    period_key   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    period_month VARCHAR2(7) NOT NULL UNIQUE,  -- YYYY-MM
    year_num     NUMBER(4)   NOT NULL,
    month_num    NUMBER(2)   NOT NULL,
    quarter_num  NUMBER(1)   NOT NULL
);

CREATE TABLE fact_commission (
    fact_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    agent_key      NUMBER NOT NULL REFERENCES dim_agent (agent_key),
    product_key    NUMBER NOT NULL REFERENCES dim_product (product_key),
    period_key     NUMBER NOT NULL REFERENCES dim_period (period_key),
    policy_id      NUMBER NOT NULL,
    split_pct      NUMBER(5, 2)  NOT NULL,
    base_premium   NUMBER(12, 2) NOT NULL,
    commission_amt NUMBER(12, 2) NOT NULL,
    loaded_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ux_fact_row UNIQUE (policy_id, agent_key, period_key)
);

EXIT;
